version: "3"
services:
    redis:
        image: "redis:5"
        ports:
            - "6379:6379"
    postgres:
        image: "postgres:12"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: postgres